#!/bin/bash

set -x

export PATH=`pwd`/autotools/install/bin:$PATH

export CFLAGS="-g -O0"

#autoreconf --install --force
#exit 0

./configure \
  --prefix=`pwd`/install \
  LDFLAGS="-libverbs" \
  --disable-silent-rules
#exit 0

make clean

make

make VERBOSE=1 V=1 install

pushd src/new/examples
  make
popd
