#!/bin/bash

set -x

export PATH=`pwd`/autotools/install/bin:$PATH

export CFLAGS="-g -O0"

autoreconf --install --force
#exit 0

installdir=`pwd`/install

rm -rf $installdir

./configure \
  --prefix=$installdir \
  LDFLAGS="-libverbs" \
  --disable-silent-rules \
  --with-spawnnet=`pwd`/spawnnet/install
#exit 0

make clean

make

make VERBOSE=1 V=1 install

pushd src/new/examples
  make
popd
