#!/usr/bin/perl -w
use strict;

# Given the name of a source directory (expected to have been
# created with norpath), copy contents to a destination directory
# on each compute node.
#
# Usage: copylibs <stagedir> <destdir>
#
# This script deletes the destdir from all nodes and recreates it
# before copying files.

# make sure we're in a slurm allocation
if (not defined $ENV{SLURM_JOBID}) {
  print "Must run from within SLURM allocation\n";
  exit 1;
}
my $jobid = $ENV{SLURM_JOBID};

if (not defined $ENV{SLURM_JOB_NUM_NODES}) {
  print "Unknown number of nodes, \$SLURM_JOB_NUM_NODES not defined\n";
  exit 1;
}
my $nodes = $ENV{SLURM_JOB_NUM_NODES};

# get our current working directory
my $pwd = `pwd`;
chomp $pwd;

# TODO: check that we got a target
if (@ARGV != 2) {
  print "Usage: preptmp <srcdir> <destdir>\n";
  exit 1;
}

# get target executable or library
my $stagedir = $ARGV[0];
print "source = $stagedir\n";

# directory to hold copies of exe and libs on each node
my $nodedir = $ARGV[1];
print "dest = $nodedir\n";

# create list of items to be copied from stagedir
#my $list = `ls $stagedir`;
#chomp $list;
#print "$list\n";
#exit 0;

# clear node directory and copy items to each compute node
#`pdsh -j $jobid "rm -rf $nodedir"`;
#`pdsh -j $jobid "mkdir -p $nodedir"`;
#`pdsh -j $jobid "cp $list $nodedir/."`;

# for SLURM, use this
print "removing $nodedir from all nodes\n";
`srun -W0 -n $nodes -N $nodes rm -rf $nodedir`;
print "creating $nodedir on all nodes\n";
`srun -W0 -n $nodes -N $nodes mkdir -p $nodedir`;
print "copying files from $stagedir to $nodedir ...\n";
`srun -W0 -n $nodes -N $nodes cp $pwd/$stagedir/* $nodedir`;
