#!/bin/bash
set -x

rm -rf stage env.stage bash.stage rsh.stage ssh.stage rcp.stage scp.stage

export LD_LIBRARY_PATH=`pwd`/../spawnnet.git/install/lib
./preplibs /bin/env
./preplibs /bin/bash
./preplibs /usr/bin/rsh
./preplibs /usr/bin/ssh
./preplibs /usr/bin/rcp
./preplibs /usr/bin/scp

mkdir stage
cp rsh.stage/* bash.stage/* ssh.stage/* rcp.stage/* scp.stage/* env.stage/* stage/.

srun -n $SLURM_NNODES -N $SLURM_NNODES rm -rf /tmp/stage
srun -n $SLURM_NNODES -N $SLURM_NNODES cp -pr `pwd`/stage /tmp/.
