#!/bin/bash

set -x

export PATH=`pwd`/../autotools/install/bin:$PATH

export CFLAGS="-g -O0"

installdir=`pwd`/install

rm -rf $installdir

autoreconf --install --force
#exit 0

make distclean

./configure \
  --prefix=$installdir \
  LDFLAGS="-libverbs" \
  --disable-silent-rules
#exit 0

make clean

make

make VERBOSE=1 V=1 install
